version: '3'
services:
  postgres:
    build: postgres/
    image: ${PG_IMAGE_NAME}
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - postgres:/var/lib/pgsql
    ports:
      - ${PG_PORT}
    restart: unless-stopped

  pgadmin4:
    build: pgadmin4/
    image: ${PGADMIN_IMAGE_NAME}
    container_name: ${PGADMIN_CONTAINER_NAME}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin4:/var/lib/pgadmin    
    ports:
      - ${PGADMIN_PORT}
    restart: unless-stopped

volumes:
       postgres:
               driver: local
               driver_opts:
                       type: 'none'
                       o: 'bind'
                       device: /data/postgres
       pgadmin4:      
              driver: local
              driver_opts:
                     type: 'none'
                     o: 'bind'
                     device: /data/pgadmin4
       

