FROM postgres:15
RUN mkdir /sql
WORKDIR /sql
COPY *.sql /sql/
#RUN su - postgres
#RUN PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -f create_tables.sql
#RUN PGPASSWORD=postgres psql -h localhost -U postgres -d postgres -f load_data.sql
